### ISSUE TITLE
Codecoverage showing 'unknown' value

### ISSUE THREAD

**Issue by rahil1304** [secheaper/cheaper#17]
Check the ReadMe file, it's showing this value, not sure why this is the case

<img width="144" alt="Screen Shot 2021-09-28 at 9 06 29 AM" src="https://user-images.githubusercontent.com/32304956/135092648-fbea5f61-4873-4f2a-a253-eebe470201a0.png">

**Comment by moksh98** [comment]
Issue has been fixed.
Since the repo name was changed, the url had to be changed for the badge
